Cria uma BasePerson para ser usada em domains
IcarusWingsBR/IcarusWings pull request #11
Opened 2024-05-15 20:13 UTC by JGranvile

BasePerson será implementada em Customer e em Payer, pois herdam os mesmos campos.

2024-05-15 20:15 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +    String details
Não entendi essa prop, qual é o uso dele?

2024-05-15 20:15 UTC, Yuri-Ferrari requested changes

2024-05-15 20:15 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +abstract class BasePerson {
Vale extender a BaseEntity aqui

2024-05-15 20:24 UTC, JGranvile commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +    String details
Para endereço, o número e o complemento

2024-05-15 20:25 UTC, JGranvile commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +abstract class BasePerson {
Certo, será feito após o PR que contém a BaseEntity ser aprovado.

2024-05-15 20:49 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +    String details
Criar um campo pra cada vai facilitar muito o uso dessas informações

2024-05-15 20:49 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +abstract class BasePerson {
Esse é o ponto, a alteração de baseEntity deveria estar ou em um PR próprio, ou aqui.

2024-05-15 20:58 UTC, JGranvile commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +    String details
Não entendi

2024-05-15 20:59 UTC, JGranvile commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +abstract class BasePerson {
Certo.

2024-05-15 22:06 UTC, Yuri-Ferrari approved these changes

2024-05-15 22:06 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BaseEntity.groovy
> +    }
```suggestion

    Date dateCreated

    Date lastUpdated

    Boolean deleted = false

    static mapping = {
        tablePerHierarchy false
    }
```

2024-05-16 10:55 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +    }
Faltou constraint do `personType`

2024-05-16 11:07 UTC, Yuri-Ferrari requested changes

2024-05-16 11:07 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BasePerson.groovy
> +    PersonType personType
O tipo desse enum não existe nesse PR

2024-05-16 17:53 UTC, Yuri-Ferrari approved these changes

2024-05-16 18:04 UTC, merged