Cria o Payment e suas derivações
IcarusWingsBR/IcarusWings pull request #18
Opened 2024-05-16 21:09 UTC by JGranvile

Cria o domain Payment com dois enums, PaymentType e PaymentStatus e também o controller e service da classe. 

Esse PR e branch tem como base a payer e o seguinte PR: https://github.com/IcarusWingsBR/IcarusWings/pull/6

2024-05-16 22:14 UTC, Yuri-Ferrari requested changes

2024-05-16 22:14 UTC, Yuri-Ferrari commented on grails-app/controllers/icaruswings/PaymentController.groovy
> +                    paymentStatus: params.paymentStatus,
O cliente deve informar o status da cobrança?

2024-05-16 22:14 UTC, Yuri-Ferrari commented on grails-app/domain/icaruswings/Payment.groovy
> +    Date dueDate
```suggestion

    Payer payer

    PaymentType paymentType

    Double value

    PaymentStatus paymentStatus

    Date dueDate
```

2024-05-16 22:14 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PaymentService.groovy
> +        payment.dueDate = parsedParams.street
Sobrou ctrl+c aqui e isso prova que o código não foi testado.
Só abram um PR quando o código estiver testado e validado.

2024-05-16 22:14 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/PaymentStatus.groovy
> +    WAITING,
Aguardando o que?

2024-05-16 22:14 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/PaymentStatus.groovy
> +    DUE,
OVERDUE é um termo melhor

2024-05-16 22:14 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/PaymentType.groovy
> +    TICKET,
Boleto não existe tradução certa em inglês, mas pra já se acostumarem no Asaas usamos o termo 'BANKSLIP'

2024-05-16 22:28 UTC, JGranvile commented on grails-app/services/icaruswings/PaymentService.groovy
> +        payment.dueDate = parsedParams.street
Eu acredito que rodei, mas não sei mt bem como testar esse método nesse caso

2024-05-16 22:28 UTC, JGranvile commented on grails-app/services/icaruswings/PaymentService.groovy
> +        payment.dueDate = parsedParams.street
De qualquer forma ajustei

2024-05-17 11:45 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PaymentService.groovy
> +        payment.dueDate = parsedParams.street
É um save, para testar chamem o endpoint e validem se está salvando no banco as informações que foram passadas para serem salvas.

2024-05-17 11:54 UTC, Yuri-Ferrari requested changes

2024-05-17 11:54 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PaymentService.groovy
> +        payment.paymentStatus = parsedParams.paymentStatus
Aqui está sendo esperado o paymentStatus mas o paymentStatus não está no map que está sendo passado.
E o comentário anterior ainda vale, pq o cliente deve informar o status? Se o cliente está criando uma cobrança não faz sentido ela ser definida com vencida ou paga, ele sempre deve estar 'esperando pagamento'

2024-05-17 13:48 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PaymentService.groovy
> +        payment.paymentStatus = parsedParams.paymentStatus
É necessário salvar algum valor, afinal o campo não aceita valor nulo, porém como descrito acima não faz sentido o cliente informar um valor, o sistema que deve definir e salvar um valor.

2024-05-17 13:49 UTC, Yuri-Ferrari requested changes
Comentário descrito acima

2024-05-17 20:08 UTC, Yuri-Ferrari approved these changes

2024-05-17 20:09 UTC, merged