Adiciona as lógicas de valicação ao Customer
IcarusWingsBR/IcarusWings pull request #21
Opened 2024-05-17 18:23 UTC by JGranvile

Lógica de validação de nome, email e CpfCnpj adicionadas ao Service do Customer

2024-05-17 20:04 UTC, Yuri-Ferrari requested changes, later dismissed
Faltou validações de endereço

2024-05-17 20:04 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/CustomerService.groovy
>          return customer
Linha 49 está setando sempre como PF

2024-05-23 13:42 UTC, welingtonloh commented on src/main/groovy/icaruswings/utils/validations/ValidateCep.groovy
> +class ValidateCep {
PostalCodeValidator

Somente para não usar verbo no nome da classe

E já se acostumarem com padrões

Vale mudar o nome do package dai tbm para .validator

2024-05-23 13:42 UTC, welingtonloh commented on src/main/groovy/icaruswings/utils/validations/ValidateCep.groovy
> +    public static Boolean isValidCep(String cep) {
public static Boolean isValid(String postalCode) { apenas, pois o nome da classe já dá o contexto

2024-05-23 13:42 UTC, welingtonloh commented on src/main/groovy/icaruswings/utils/validations/ValidateCep.groovy
> +        if(!StringUtils.containsOnlyNumbers(cep)) return false
```suggestion
        if (!StringUtils.containsOnlyNumbers(cep)) return false
```

2024-05-23 13:42 UTC, welingtonloh commented on src/main/groovy/icaruswings/utils/validations/ValidateCep.groovy
> +    public static Boolean ValidateExistingCep(String cep) {
método com inicial em minusculo

2024-05-23 13:42 UTC, welingtonloh commented on grails-app/services/icaruswings/CustomerService.groovy
> +
Pode remover essa linha em branco

2024-05-23 13:42 UTC, welingtonloh commented on grails-app/services/icaruswings/CustomerService.groovy
> +        Customer validateCustomer = validateCustomerParams(parsedParams)
```suggestion
        Customer validatedCustomer = validateCustomer(parsedParams)
```

2024-05-23 13:42 UTC, welingtonloh commented on grails-app/services/icaruswings/CustomerService.groovy
> +        }
Isso aqui vcs podem resolver dentro da adapter

2024-05-23 13:42 UTC, welingtonloh commented on grails-app/services/icaruswings/CustomerService.groovy
> +        if(!parsedParams.name) {
```suggestion
        if (!parsedParams.name) {
```

2024-05-23 13:42 UTC, welingtonloh commented on grails-app/services/icaruswings/CustomerService.groovy
> +        }
Essa lógica tem que estar no nosso adapter, sugiro remover desse PR e tratar no PR do adapter apenas

2024-05-23 13:46 UTC, welingtonloh commented on grails-app/services/icaruswings/CustomerService.groovy
> +    private Customer validateCustomerParams(Map parsedParams) {
Chama apenas de validateSave

Pois customer já sabemos que é pelo nome da service

E params se torna desnecessário

2024-05-23 20:18 UTC, welingtonloh commented on build.gradle
> +    implementation 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1'
tenta merge com a main agora

2024-05-24 12:49 UTC, welingtonloh approved these changes

2024-05-24 16:58 UTC, merged