Adiciona as validações para as props do Payer
IcarusWingsBR/IcarusWings pull request #22
Opened 2024-05-17 19:51 UTC by Tcheagow

Adiciona as validações para as props do Payer

2024-05-17 20:15 UTC, Yuri-Ferrari requested changes, later dismissed

2024-05-17 20:15 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PayerService.groovy
> +        }
CEP também deve ser apenas números

2024-05-23 13:47 UTC, welingtonloh commented on build.gradle
> +    implementation 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1'
Vcs estão atualizando as branches de PRs já abertos diariamente?

É o segundo PR que essa linha aparece como "alteração"

2024-05-23 13:47 UTC, welingtonloh commented on grails-app/services/icaruswings/PayerService.groovy
> +        }
Mesmo lance, pode remover desse PR e implementar isso no PR que tem a adapter para Payer

2024-05-23 13:47 UTC, welingtonloh commented on grails-app/services/icaruswings/PayerService.groovy
> +    private Payer validatePayerParams(Map parsedParams) {
validateSave

2024-05-23 17:55 UTC, JGranvile commented on build.gradle
> +    implementation 'org.codehaus.groovy.modules.http-builder:http-builder:0.7.1'
Verificando

2024-05-23 18:11 UTC, JGranvile commented on grails-app/services/icaruswings/PayerService.groovy
> +        }
Deixando estático pela necessidade da hora de salvar

2024-05-24 12:51 UTC, welingtonloh commented on grails-app/services/icaruswings/PayerService.groovy
> +        Payer validatePayer = validateSave(parsedParams)
```suggestion
        Payer validatedPayer = validateSave(parsedParams)
```
De pagador validado, como validate significa validar, nao podemos ter objeto com verbo

2024-05-24 12:51 UTC, welingtonloh commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.number = Integer.parseInt(parsedParams.number)
Esse deveria ser o addressNumber?

2024-05-24 17:04 UTC, JGranvile commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.number = Integer.parseInt(parsedParams.number)
Não, ainda não está trocado na domain essas mudanças de nomes

2024-05-24 17:05 UTC, JGranvile commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.number = Integer.parseInt(parsedParams.number)
Imaginei que seria melhor depois que fosse tudo mergeado, criar uma branch e trocar os nomes que foram alterados no adapter. Isso veio do pensamento tbm que seria errado mexer na domain de uma branch criada pelo adapter, mas os testes foram feitos também levando isso em consideração .

2024-05-24 21:00 UTC, JGranvile commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.number = Integer.parseInt(parsedParams.number)
atualização: esse problema foi resolvido a partir da payer-adapter.

2024-05-28 02:53 UTC, TuiNascimento commented on grails-app/services/icaruswings/PayerService.groovy
> +        }
Para if's que tem apenas uma linha, procurem sempre utilizar if inline, da seguinte forma:

```suggestion
        if (validatedPayer.hasErrors()) throw new ValidationException("Não foi possível salvar o pagador", validatedPayer.errors)
        
```

É apenas padrão de estilo do código que usamos no Asaas, torna mais simples

2024-05-28 02:58 UTC, TuiNascimento commented on grails-app/services/icaruswings/PayerService.groovy
> +        }
Não precisa validar isso aqui. O domain já tem as constraints que garantem que não vai ser null.

2024-05-28 02:58 UTC, TuiNascimento commented on src/main/groovy/icaruswings/utils/validator/CheckEntityExistenceById.groovy
> +class CheckEntityExistenceById {
https://github.com/IcarusWingsBR/IcarusWings/pull/51#discussion_r1616501465

2024-05-28 22:36 UTC, TuiNascimento approved these changes

2024-05-28 22:36 UTC, merged