Refatorando Customer(Service e controller) para nova branch
IcarusWingsBR/IcarusWings pull request #5
Opened 2024-05-15 18:59 UTC by JGranvile

Refatora Customer da branch controller para uma nova branch dedicada ao Customer e adicionar sua Domain, Service e Controller.

2024-05-15 20:20 UTC, Yuri-Ferrari requested changes
Esse PR deve se basear no PR que cria o BasePerson

2024-05-15 20:36 UTC, JGranvile commented
> Esse PR deve se basear no PR que cria o BasePerson

O base person foi criado depois na linha do tempo do código, não sei como fica nesse caso.

2024-05-15 21:12 UTC, Yuri-Ferrari commented
> > Esse PR deve se basear no PR que cria o BasePerson
> 
> O base person foi criado depois na linha do tempo do código, não sei como fica nesse caso.

1. Fechar o PR;
2. A branch do BasePerson deve ser mergeada nessa;
3. Realizar as alterações;
4. Na parte superior do PR tem um 'Edit', clicando nele será possível trocar a branch base de `main` para a branch do BasePerson`
5. Reabrir o PR adicionando na descrição o link do PR que precede este.

2024-05-16 11:07 UTC, Yuri-Ferrari requested changes

2024-05-16 11:07 UTC, Yuri-Ferrari commented on grails-app/domain/icaruswings/Customer.groovy
> +        cpfCnpj nullable: false, blank: false, size: 11..18, unique: true
Por que as constraint email: true e size estão aqui e não na BasePerson? Além disso, nullable e blank já estão definidas lá

2024-05-16 11:07 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/CustomerService.groovy
> +        customer.personType = PersonType.NATURAL
Agora que o Customer extende o BasePerson, está faltando bastante campos que não aceitam valores nulos

2024-05-16 16:53 UTC, Tcheagow commented on grails-app/domain/icaruswings/Customer.groovy
> +        cpfCnpj nullable: false, blank: false, size: 11..18, unique: true
a gente colocou aqui, pois a ideia seria de sobrescrever essas duas, visto que ambas serão únicas para o Customer, mas não serão únicas para o Payer

2024-05-16 19:01 UTC, Yuri-Ferrari requested changes

2024-05-16 19:01 UTC, Yuri-Ferrari commented on grails-app/controllers/icaruswings/CustomerController.groovy
> +            Customer customer = customerService.save(params)
Por que aqui não é criado um map de parse como é feito no Payer?

2024-05-16 19:01 UTC, Yuri-Ferrari commented on grails-app/domain/icaruswings/Customer.groovy
> +import icaruswings.utils.PersonType
Esse import não é utilizado e pode ser removido

2024-05-16 19:52 UTC, Yuri-Ferrari requested changes

2024-05-16 19:52 UTC, Yuri-Ferrari commented on grails-app/controllers/icaruswings/CustomerController.groovy
> +            Customer customer = customerService.save(params)
Map criado não é passado como parâmetro

2024-05-16 19:52 UTC, Yuri-Ferrari commented on grails-app/domain/icaruswings/Customer.groovy
> +class Customer extends BasePerson{
```suggestion
class Customer extends BasePerson {
```

2024-05-16 22:07 UTC, Yuri-Ferrari approved these changes

2024-05-16 22:18 UTC, merged