Adiciona domain, controller e services do Payer
IcarusWingsBR/IcarusWings pull request #6
Opened 2024-05-15 19:07 UTC by Tcheagow

Esse pull request cria o domain, controller e services do Payer

2024-05-15 20:16 UTC, Yuri-Ferrari requested changes

2024-05-15 20:16 UTC, Yuri-Ferrari commented on grails-app/controllers/icaruswings/PayerController.groovy
> +
```suggestion
            Payer payer = payerService.save(parsedParams)

            redirect(action: "show", id: payer.id)
```

2024-05-15 20:16 UTC, Yuri-Ferrari commented on grails-app/controllers/icaruswings/PayerController.groovy
> +
```suggestion
```

2024-05-15 20:16 UTC, Yuri-Ferrari commented on grails-app/controllers/icaruswings/PayerController.groovy
> +
```suggestion
```

2024-05-15 20:55 UTC, Yuri-Ferrari requested changes

2024-05-15 20:55 UTC, Yuri-Ferrari commented on src/main/groovy/icaruswings/utils/BaseEntity.groovy
Conforme conversado em outro PR, essa alteração foge do escopo desse PR que é 'Domain, Controller e Service do Payer' e portanto não deve fazer parte desse PR

2024-05-15 20:55 UTC, Yuri-Ferrari commented on grails-app/domain/icaruswings/Payer.groovy
> +class Payer extends icaruswings.utils.BaseEntity {
Payer deve extender o BasePerson, não o BaseEntity

2024-05-16 11:08 UTC, Yuri-Ferrari requested changes

2024-05-16 11:08 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.save(failOnError: true)
Como o Payer extende o BasePerson, está faltando bastante campos que são nullable false

2024-05-16 11:08 UTC, Yuri-Ferrari commented on grails-app/conf/application.yml
Essas alterações não fazem parte desse PR

2024-05-16 18:59 UTC, Yuri-Ferrari requested changes

2024-05-16 18:59 UTC, Yuri-Ferrari commented on grails-app/conf/application.yml
Alterações neste arquivi não são referentes ao contexto desse PR e devem ser removidas do mesmo

2024-05-16 18:59 UTC, Yuri-Ferrari commented on build.gradle
Alterações neste arquivi não são referentes ao contexto desse PR e devem ser removidas do mesmo

2024-05-16 18:59 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.customer = payer.get(parsedParams.customerId)
Essa linha não foi testada.

2024-05-16 19:00 UTC, Yuri-Ferrari requested changes

2024-05-16 19:00 UTC, Yuri-Ferrari commented on grails-app/domain/icaruswings/Payer.groovy
> +    Customer customer
Customer não existe nessa branch.

2024-05-16 22:09 UTC, Yuri-Ferrari requested changes

2024-05-16 22:09 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.customer = payer.get(parsedParams.customerId)
O erro persiste.

2024-05-16 22:09 UTC, Yuri-Ferrari commented on grails-app/conf/application.yml
Alterações sem relação com esse PR. Remover do mesmo

2024-05-16 22:56 UTC, Tcheagow commented on grails-app/conf/application.yml
erro arrumado.

2024-05-16 22:59 UTC, Tcheagow commented on grails-app/conf/application.yml
O git aponta uma alteração que não conseguimos identificar. Para nós, está exatamente igual.

2024-05-17 11:43 UTC, Yuri-Ferrari requested changes

2024-05-17 11:43 UTC, Yuri-Ferrari commented on grails-app/services/icaruswings/PayerService.groovy
> +        payer.city = parsedParams.neighborhood
Sobrou algo do ctrl+c, sempre testem os códigos antes de commitar

2024-05-17 13:45 UTC, Yuri-Ferrari approved these changes
Não esqueçam de mudar a base branch antes de mergear

2024-05-17 17:37 UTC, merged